name: CI for github-action-poc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Hit external API and print HTTP status and response
        run: |
          response=$(curl -s -w "%{http_code}" -o response_body.txt https://api.restful-api.dev/objects/7)
          echo "HTTP Status: $response"
          echo "Response Body:"
          cat response_body.txt
